[server]
host = "127.0.0.1"
port = 8080

[data]
storage = "./"
all_programs_file = "programs.json"
all_courses_file = "courses.json"

[log]
level = "info"
with_target = true

[fetching]
programs_url = "https://iq5prod1.smartcatalogiq.com/apis/progAPI?path=/sitecore/content/Catalogs/Union-University/2023/Academic-Catalogue-Undergraduate-Catalogue&format=json"
courses_url = "https://iq5prod1.smartcatalogiq.com/apis/courseAPI?path=/sitecore/content/Catalogs/Union-University/2023/Academic-Catalogue-Undergraduate-Catalogue&format=json"

[cors]
origins = []

[static_assets]
dir = "./dist"
